### PR TITLE
Preparation for publication on PyPI

### PR DESCRIPTION
**Pull request by pklaus**
@Araneidae @thomascobb

This change set prepares the package for publication on the Python Package Index (PyPI).
Strictly speaking, the changes are not even necessary. But they follow the usual conventions of adding a link to the Github repository and including the ReStructured text README in the long description (and thus the package's details on PyPI).

With the commands

```
export MODULEVER=1.4.dev0
python setup.py sdist
python setup.py bdist_wheel --universal

twine upload --repository testpypi dist/*
# ^ here, you will be asked for credentials from test.pypi.org
```

I uploaded two pre-release files from the dist folder (`epicsdbbuilder-1.4.dev0-py2.py3-none-any.whl` and `epicsdbbuilder-1.4.dev0.tar.gz`) to the **test** version of the Python Package Index ([test.pypi.org](https://test.pypi.org/)):

https://test.pypi.org/project/epicsdbbuilder/1.4.dev0/

So that's just to document the steps necessary.
I leave the decision and subsequent uploading to the actual (non-test) PyPI to you (unless you tell me otherwise).

### CODE REVIEW

**Comment by pklaus** [comment]
I also had a look at the Makefile. Looks outdated an unnecessary as of today. For the reasoning, see 62d6fe8.

**Comment by thomascobb** [comment]
I will discuss with @Araneidae about this.

**Comment by Araneidae** [comment]
@thomascobb , is this merge request now obsoleted by #11 ?

**Comment by thomascobb** [comment]
> @thomascobb , is this merge request now obsoleted by #11 ?

yes

**Comment by Araneidae** [comment]
Obsoleted by #11, now merged.

**Pull request closed without merging**
